### ISSUE TITLE
Partial update of E-paper every minute

### ISSUE THREAD

**Issue by SloeComputers** [AnotherJohnH/picoPloT#1]
for accurate time display

**Comment by AnotherJohnH** [comment]
has been implemented with[ ](https://github.com/AnotherJohnH/picoPloT/commit/bf42740fd65849e89d6ecad63aa5e13b16bcd973)

**Comment by SloeComputers** [comment]
has been implemented with [patch](https://github.com/AnotherJohnH/picoPloT/commit/29638865d3c468fba72435aa926bce5a9fae1661)

**Comment by AnotherJohnH** [comment]
has been implemented with this [patch] (https://github.com/AnotherJohnH/picoPloT/commit/29638865d3c468fba72435aa926bce5a9fae1661)
